# Generated by Django 4.1.1 on 2022-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_description', models.TextField(max_length=100)),
                ('burger_name', models.CharField(max_length=200)),
                ('burger_description', models.TextField(max_length=100)),
                ('loc_lon', models.CharField(max_length=200)),
                ('loc_lat', models.CharField(max_length=200)),
            ],
        ),
    ]
