# Generated by Django 4.1.1 on 2022-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_restaurant_burger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='burger_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.TextField(max_length=1000),
        ),
    ]
