# Generated by Django 4.1.1 on 2022-10-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_restaurant_burger_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurants',
        ),
    ]
