# Generated by Django 4.1.1 on 2022-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_restaurants_burger_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='restaurant_adresse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='restaurant_site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
