# Generated by Django 4.1.1 on 2022-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_restaurants_restaurant_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('status', models.CharField(default='disponible', max_length=100)),
            ],
        ),
    ]
