# Generated by Django 4.1.1 on 2022-10-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='code',
            new_name='value',
        ),
    ]
