# Generated by Django 4.1.1 on 2022-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_rename_code_codes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='nb_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='note_moyenne',
            field=models.FloatField(default=0),
        ),
    ]
