# Generated by Django 4.1.1 on 2023-02-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_restaurants_nb_votes_restaurants_note_moyenne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('NPA', models.IntegerField()),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('adresse_mail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
