# Generated by Django 4.1.1 on 2023-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_textaccueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLeConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_p_1_1', models.CharField(blank=True, max_length=2000, null=True)),
                ('text_p_1_2', models.CharField(blank=True, max_length=2000, null=True)),
                ('text_p_1_3', models.CharField(blank=True, max_length=2000, null=True)),
                ('text_p_3_1', models.CharField(blank=True, max_length=2000, null=True)),
                ('text_p_3_2', models.CharField(blank=True, max_length=2000, null=True)),
                ('text_p_3_3', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
