# Generated by Django 4.1.1 on 2023-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_textleconcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_item_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_item_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_item_3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_item_4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_item_5',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='textleconcours',
            name='text_p_2_item_6',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
